version: "3.8"

services:
    frontend:
        build: .
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true # Fix for file watching in Docker
        stdin_open: true
        tty: true
